# Generated by Django 5.1.5 on 2025-02-16 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apaeropuerto', '0002_alter_usuario_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='vuelo',
            field=models.ManyToManyField(related_name='reserva_vuelo', to='apaeropuerto.vuelo'),
        ),
        migrations.AlterField(
            model_name='contactoaeropuerto',
            name='aeropuerto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contacto_de_aeropuerto', to='apaeropuerto.aeropuerto'),
        ),
    ]
